steal(
	'canui/layout/sortable',
	'canui/layout/wrap',
	'canui/layout/fill',
	'canui/layout/bgiframe',
	'canui/layout/positionable',
	'canui/layout/block',
	'canui/layout/split',
	'canui/layout/resize',
	'canui/layout/table_scroll',
	'canui/layout/modal'
).then(
	'canui/nav/accordion',
	'canui/nav/slider',
	'canui/nav/selectable'
).then(
	'canui/util/scrollbar_width'
)